source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXPopover_Example', :exclusive => true do
  pod "BXPopover", :path => "../"
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end

target 'BXPopover_Tests', :exclusive => true do
  pod "BXPopover", :path => "../"

  
end
