source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXPopover_Example', :exclusive => true do
  pod "BXPopover", :path => "../"
end

target 'BXPopover_Tests', :exclusive => true do
  pod "BXPopover", :path => "../"

  
end
